### ISSUE TITLE
Available Test Data

### ISSUE THREAD

**Issue by mgopez** [chadlaing/feht#1]
Is there any test data that can be supplied?
For example, in the instructions it mentions that inputs are `metadata.txt`, and `data.tab`.
I would need this test data in order to write a conda wrapper for feht.

**Comment by mgopez** [comment]
Oh oops, I added the --delimiter flag and used the data in the data/ folder.

**Comment by chadlaing** [comment]
Hi Matt,

Thanks for making the conda wrapper.
I'm working on an update for Genevieve that I will push up next week to address some of the issues she was having, which will include additional tests.

Let me know if you need anything.

Chad
